// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: demo.proto

package protoModel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Demo service

func NewDemoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		&api.Endpoint{
			Name:    "Demo.Info",
			Path:    []string{"/demo/info"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
}

// Client API for Demo service

type DemoService interface {
	Info(ctx context.Context, in *CommReq, opts ...client.CallOption) (*DemoResp, error)
}

type demoService struct {
	c    client.Client
	name string
}

func NewDemoService(name string, c client.Client) DemoService {
	return &demoService{
		c:    c,
		name: name,
	}
}

func (c *demoService) Info(ctx context.Context, in *CommReq, opts ...client.CallOption) (*DemoResp, error) {
	req := c.c.NewRequest(c.name, "Demo.Info", in)
	out := new(DemoResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Demo service

type DemoHandler interface {
	Info(context.Context, *CommReq, *DemoResp) error
}

func RegisterDemoHandler(s server.Server, hdlr DemoHandler, opts ...server.HandlerOption) error {
	type demo interface {
		Info(ctx context.Context, in *CommReq, out *DemoResp) error
	}
	type Demo struct {
		demo
	}
	h := &demoHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "Demo.Info",
		Path:    []string{"/demo/info"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&Demo{h}, opts...))
}

type demoHandler struct {
	DemoHandler
}

func (h *demoHandler) Info(ctx context.Context, in *CommReq, out *DemoResp) error {
	return h.DemoHandler.Info(ctx, in, out)
}
