group="mega-web"
name="activity"
region="cn"
ip="192.168.1.255"
nodeId="1"
env="local"
httpPort=9949
rpcPort=52887
webSocketPort=9949
kafkaHookAddrs=["192.168.2.20:9092"]
[Custom]
    sendDing=""
    sentryDsn=""
    kafkaHookTopic=""
    phpMainUrl=""