app:
  group: mega-web
  name: activity
  region: cn
  ip: 192.168.2.0
  nodeId: 1
  env: local
  httpPort: 8858
  rpcPort: 52888
  webSocketPort: 9949
  custom:
    sendDing: ""
    sentryDsn: ""
    kafkaHookTopic: ""
    phpMainUrl: ""
log:
  kafkaHookAddrs:
    - 192.168.2.20:9092
configCenter:
  consulAddrs:
    - 192.168.2.20:8500
  confKey: werewolf_conf
consul:
  addrs:
    - 192.168.2.20:8500
  confKey: werewolf_conf
kafka:
  addrs:
    - 192.168.2.20:9092
  topic: ""
mongo:
  default:
    addr: mongodb://192.168.2.20:27017
    dbName: test
    username: admin
    password: ""
mysql:
  master:
    dsn: mega:mega(192.168.2.20:3306)/mega?charset=utf8mb4&parseTime=True&loc=Local
    warnThreshold: 50
  slave:
    dbName: mega
    addr: 192.168.2.20:3306
    username: mega
    password: mega"
    charset: utf8mb4
    warnThreshold: 50
redis:
  db0:
    addr: 112.124.15.145:6379
    password: ""
    database: 0
  db1:
    sentinel:
      master: mymaster
      nodes:
        - 192.168.2.20:27000
    database: 1