app:
  group: mega-web
  name: activity
  region: cn
  ip: 192.168.2.0
  nodeId: 1
  env: prod
  httpPort: 8858
  rpcPort: 52888
  webSocketPort: 9949
  custom:
    sendDing: "http://dingUrl"
    sentryDsn: "http://dsn"
    phpMainUrl: ""
log:
  kafkaHookEnable: false
  kafkaHookAddrs:
    - localhost:9092
  kafkaHookTopic: ""
  logoutPath: "/home/hammer/Desktop/goProjects/mega-go-micro/demo/logout"
  maxDay: 30
  level: debug
configCenter:
  enable: false
  consulAddrs:
    - localhost:8500
  confKey: werewolf_conf
consul:
  addrs:
    - localhost:8500
  confKey: werewolf_conf
kafka:
  enable: false
  addrs:
    - localhost:9092
  topic: ""
  dialTimeout: 2
mongo:
  default:
    enable: true
    addr: mongodb://localhost:27017/?maxPoolSize=500&minPoolSize=10
    dbName: test
    username: admin
    password: ""
mysql:
  default:
    enable: true
    master:
      dsn: mega:mega@tcp(localhost:3306)/mega?charset=utf8mb4&parseTime=True&loc=Local
      warnThreshold: 50
      debugInfo: true
    slave:
      dsn: mega:mega@tcp(localhost:3306)/mega?charset=utf8mb4&parseTime=True&loc=Local
      warnThreshold: 50
  db1:
    enable: false
    master:
      dsn: mega:mega@tcp(localhost:3306)/mega?charset=utf8mb4&parseTime=True&loc=Local
      warnThreshold: 50
redis:
  default:
    enable: true
    addr: 127.0.0.1:6379
    password: ""
    database: 0
  db1:
    enable: false
    sentinel:
      master: mymaster
      nodes:
        - 127.0.0.1:27000
    database: 1
tracer:
  enable: false
  tracerType: skyWalking
  addr: 127.0.0.1:11800
