group = "mega-web"
name = "activity"
region = "cn"
ip = "192.168.2.0"
nodeId = "1"
env = "local"
httpPort = 8858
rpcPort = 52888
webSocketPort = 9949
kafkaHookAddrs = ["192.168.2.20:9092"]
[Custom]
sendDing = ""
sentryDsn = ""
kafkaHookTopic = ""
phpMainUrl = ""