app:
  group: mega-web
  name: activity
  region: cn
  ip: 192.168.2.0
  nodeId: 1
  env: prod
  httpPort: 8858
  rpcPort: 52888
  webSocketPort: 9949
  custom:
    sendDing: "http://dingUrl"
    sentryDsn: "http://dsn"
    kafkaHookTopic: ""
    phpMainUrl: ""
log:
  kafkaHookEnable: false
  kafkaHookAddrs:
    - 192.168.2.20:9092
  kafkaHookTopic: ""
  logoutPath: "/home/hammer/Desktop/goProjects/mega-go-micro/log"
  maxDay: 30
configCenter:
  enable: false
  consulAddrs:
    - 192.168.2.20:8500
  confKey: werewolf_conf
consul:
  addrs:
    - 192.168.2.20:8500
  confKey: werewolf_conf
kafka:
  enable: true
  addrs:
    - 192.168.2.20:9092
  topic: ""
mongo:
  default:
    enable: true
    addr: mongodb://192.168.2.20:27017
    dbName: test
    username: admin
    password: ""
mysql:
  db0:
    enable: true
    master:
      dsn: mega:mega(192.168.2.20:3306)/mega?charset=utf8mb4&parseTime=True&loc=Local
      warnThreshold: 50
    slave:
      dsn: mega:mega(192.168.2.20:3306)/mega?charset=utf8mb4&parseTime=True&loc=Local
      warnThreshold: 50
  db1:
    enable: true
    master:
      dsn: mega:mega(192.168.2.20:3306)/mega?charset=utf8mb4&parseTime=True&loc=Local
      warnThreshold: 50
redis:
  db0:
    enable: true
    addr: 127.0.0.1:6379
    password: ""
    database: 0
  db1:
    enable: true
    sentinel:
      master: mymaster
      nodes:
        - 127.0.0.1:27000
    database: 1